requirejs.config({
	baseUrl: 'js',
	paths: {
		jquery: [
			'vendor/jquery.min'
		],
		bootstrap: 'vendor/bootstrap.min',
		bootstrapValidator: 'vendor/validator.min',
		slick: 'vendor/slick.min',
		perfectScrollbarJQuery: 'vendor/perfect-scrollbar.jquery.min',
		perfectScrollbar: 'vendor/perfect-scrollbar.min',
		dateTimePicker: 'vendor/bootstrap-datetimepicker.min',
		modernizr: 'vendor/modernizr',
		jqueryUI: 'vendor/jquery-ui-custom.min',
		placeholder: 'vendor/jquery.placeholder.min',
		main: 'main',
		login: 'login',
		dataFilter: 'data-filter',
		graphPanelCard: 'graph-panel-card',
		createAccount: 'create-account',
		bootstrapSelect: 'vendor/bootstrap-select.min',
		bootstrapSelectPicker: 'bootstrap-select-picker',
		customScrollbar: 'custom-scrollbar',
		addCardPopup: 'add-card-popup',
		tooltip: 'tooltip',
		contactMethod: 'contact-method',
		editLowBalance: 'edit-low-balance',
		footerDashboard: 'footer-dashboard',
		transactionHistoryTable: 'transaction-history-table',
		placeholderInput: 'placeholder-input',
		paginationBundle: 'vendor/jplist.pagination-bundle.min',
		jplistCore: 'vendor/jplist.core.min',
		pagination: 'pagination',
		messageAlerts: 'message-alerts'
	},

	shim: {
		'bootstrap': ['jquery'],
		'main': ['slick', 'perfectScrollbarJQuery'],
		'login': ['jquery', 'bootstrap', 'bootstrapValidator'],
		'bootstrapValidator': ['jquery', 'bootstrap'],
		'dataFilter': ['jquery', 'bootstrap'],
		'graphPanelCard': ['bootstrap'],
		'dateTimePicker': ['jquery'],
		'createAccount': ['dateTimePicker', 'jquery', 'jqueryUI'],
		'bootstrapSelect':['jquery', 'bootstrap'],
		'bootstrapSelectPicker':['bootstrapSelect'],
		'customScrollbar': ['perfectScrollbarJQuery'],
		'addCardPopup': ['jquery', 'bootstrapSelectPicker'],
		'tooltip': ['jquery'],
		'contactMethod': ['jquery'],
		'editLowBalance':['jquery'],
		'modernizr':['jquery','bootstrap'],
		'jqueryUI': ['jquery'],
		'transactionHistoryTable': ['jquery'],
		'placeholder': ['jquery'],
		'placeholderInput': ['placeholder'],
		'pagination':['jquery', 'jplistCore', 'paginationBundle' ],
		'messageAlerts': ['jquery'],
	}
});
		
